CREATE TABLE staffs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'スタッフID',
    name VARCHAR(100) NOT NULL COMMENT 'スタッフ名（名字）',
    password VARCHAR(255) NOT NULL COMMENT 'パスワード（ハッシュ化）',
    access ENUM('STAFF', 'SENIOR', 'ADMIN') NOT NULL COMMENT '権限区分',
    is_active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '有効フラグ（退職・一時停止対応）',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='スタッフ管理テーブル';
