CREATE TABLE orders (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '注文ID',
    customer_id INT UNSIGNED NOT NULL COMMENT '顧客ID（外部キー）',
    status ENUM('ORDERED', 'PREPARING', 'SERVED', 'CANCELLED') NOT NULL DEFAULT 'ORDERED' COMMENT 'ステータス',
    served_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '全ての明細が提供済みになった日時',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',

    CONSTRAINT fk_orders_customers_id
        FOREIGN KEY (customer_id)
        REFERENCES customers(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='注文テーブル';
