CREATE TABLE visit_groups (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '顧客グループID',
    group_token VARCHAR(64) NOT NULL UNIQUE COMMENT 'トークン',
    table_number INT UNSIGNED NOT NULL COMMENT '卓番号',
    number_of_people INT UNSIGNED NOT NULL COMMENT '何名様',
    status ENUM('ACTIVE', 'INACTIVE', 'EXPIRED') NOT NULL DEFAULT 'ACTIVE' COMMENT '状態',
    expired_at TIMESTAMP NULL DEFAULT NULL COMMENT '有効期限',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='来店グループ（1組）管理';
